name: Build Linux Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: |
          go mod tidy
          go build -o memory-alert app.go

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: memory-alert-linux
          path: ./memory-alert
